[TELNET] Add missing curly braces to for-statement
Fixes GCC 8 warning:
base/applications/network/telnet/src/tnmain.cpp:171:8: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
        for (j = cursor; j >= 0; j--)
        ^~~
base/applications/network/telnet/src/tnmain.cpp:174:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'for'
         for (k = --j; k >= 0; k--)
         ^~~