[WININET] Fix missing braces (from wine-10.0)
Fixes GCC 13 warning about misleading indentation.

C:/ReactOS/reactos/modules/rostests/winetests/advapi32/cred.c: In function 'func_cred':
C:/ReactOS/reactos/modules/rostests/winetests/advapi32/cred.c:809:5: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
  809 |     else
      |     ^~~~
In file included from C:/ReactOS/reactos/modules/rostests/winetests/advapi32/cred.c:28:
C:/ReactOS/reactos/sdk/include/wine/test.h:168:31: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
  168 | #define trace_(file, line)    (winetest_set_location(file, line), 0) ? (void)0 : winetest_trace
      |                               ^
C:/ReactOS/reactos/sdk/include/wine/test.h:176:18: note: in expansion of macro 'trace_'
  176 | #define trace    trace_(__FILE__, __LINE__)
      |                  ^~~~~~
C:/ReactOS/reactos/modules/rostests/winetests/advapi32/cred.c:812:9: note: in expansion of macro 'trace'
  812 |         trace("domain password:\n");
      |         ^~~~~