[0.4.14][DBGHELP] Addendum to last commit CORE-17073 (#3257)
I do recommend to change in function SymSetSearchPath: the line
WCHAR* sp;
to
WCHAR* sp = NULL;

to avoid the following compiler warning, that I got only on carrier-releaser interestingly,

../dll/win32/dbghelp/dbghelp.c: In function 'SymSetSearchPath':
../dll/win32/dbghelp/dbghelp.c:244:9: error: 'sp' may be used uninitialized in this function [-Werror=uninitialized]
cc1: all warnings being treated as errors

but I did not get that error on compilation when building this locally on "GCC4.7.2 RosBE2.1.6"
or "GCC8.4.0 RosBE2.21", or "VS2010", or with the buildbits/testbots. Weird!
I have no clue, why carrier releaser does behave different here at all upon compilation!