[KDGDB] Fix build with MSVC.
gdb_input.c(243): error C4477: '_snprintf' : format string '%p' requires an argument of type 'void *', but variadic argument 1 has type 'UINT_PTR'

i386_sup.c(98): error C4090: 'return': different 'const' qualifiers

For that latter fix, I'm not fully sure of the intent of the original
code, and whether a better fix could be made instead of dropping 'const'.