[0.4.8][NTOSKRNL][SDK] Regression, MSVC build fails -DCMAKE_BUILD_TYPE=Release
'ninja ntoskrnl' failed on all MSVC compilers because:
ntoskrnl\config\ntapi.c(1097) : error C2065: 'UNIMPLEMENTED_ONCE' : undeclared identifier

It regressed by
0.4.8-dev-650-g 81eb3bbceb518c331f3d8e4754ad61adc0e94d33 (macro defined, but MSVC Release forgotten) and
0.4.8-dev-651-g 7b398514f1ff921edb647b8d7e01941670a79034 (macro used)

fix picked from 0.4.9-dev-622-g c704cf5f87a818bda66bfad8cb75badedfc5c208

I tested: after that fix I can build the whole bootcd in debug and release configuration with
MSVC 16.0.40219.1 (VS2010SP1)

Ftr The VS2010 Release configuration bootcd will crash during 2nd stage still, but that is unrelated.