[CMAKE:MSVC] Add warning C4090 (different 'modifier' qualifiers -- for C programs only; for C++ programs, the compiler error C2440 is issued --) as an error (usually, when I hit this warning, it means that I'm doing an error in my code...). This warning can be caused when a pointer to a const or volatile item is assigned to a pointer not declared as pointing to const or volatile. This warning is already treated as an error by GCC...
svn path=/trunk/; revision=60100