[KERNEL32] Fix 2 'unused-but-set-variable' when compiling as NT6+
{{
.../dll/win32/kernel32/client/vista.c: In function 'SleepConditionVariableCS':
.../dll/win32/kernel32/client/vista.c:44:20: error: variable 'TimeOutPtr' set but not used [-Werror=unused-but-set-variable]
.../dll/win32/kernel32/client/vista.c: In function 'SleepConditionVariableSRW':
.../dll/win32/kernel32/client/vista.c:79:20: error: variable 'TimeOutPtr' set but not used [-Werror=unused-but-set-variable]
}}

CORE-12596