[NTDLL_APITEST] Suppress GCC 13 infinite-recursion warning
Suppress warning about infinite recursion, because that is the whole point of this test.

C:/ReactOS/reactos/modules/rostests/apitests/ntdll/StackOverflow.c: In function 'infinite_recursive':
C:/ReactOS/reactos/modules/rostests/apitests/ntdll/StackOverflow.c:23:1: error: infinite recursion detected [-Werror=infinite-recursion]
   23 | infinite_recursive(void)
      | ^~~~~~~~~~~~~~~~~~
C:/ReactOS/reactos/modules/rostests/apitests/ntdll/StackOverflow.c:58:5: note: recursive call
   58 |     infinite_recursive();
      |     ^~~~~~~~~~~~~~~~~~~~