[0.4.14][SYSSETUP] Fix broken build on RosBE2.1.6 CORE-17028
The build broke due to a typo introduced by
0.4.15-dev-275-g
612729b09272aeb693e156de6b5991891951dbf2

../dll/win32/syssetup/wizard.c: In function 'ProductPageDlgProc':
../dll/win32/syssetup/wizard.c:527:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-
after-statement]
cc1.exe: all warnings being treated as errors

fix cherry-picked from 0.4.15-dev-278-g
4cbb21761cde71af7ad47573099ca92d966c8920
-------------------------
[0.4.14][SYSSETUP][BOOTDATA] Make Server default again and write Service Pack (#2749)

- Make "ReactOS Server" the default product option again instead of "ReactOS Workstation".
- Write "Service Pack" info onto registry.
- Add ProductOption option to bootcd unattend.inf.
- Delete IDC_PRODUCT_SUITE and IDC_PRODUCT_TYPE controls.

To fix regression with Visual Studio 2010 setup CORE-17028

I took 2 translation files in their most recent version from master 0.4.15-dev-275-g
612729b to prevent having to resolve any conflicts manually:
tr-TR.rc
uk-UA.rc

cherry picked from commit 0.4.15-dev-275-g
612729b09272aeb693e156de6b5991891951dbf2