[RSAENH] Use StringCbPrintfA instead of sprintf
Fixes GCC 8 warning:
dll/win32/rsaenh/rsaenh.c:161:23: error: '%s' directive writing up to 259 bytes into a region of size 235 [-Werror=format-overflow=]
 #define RSAENH_REGKEY "Software\\Wine\\Crypto\\RSA\\%s"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dll/win32/rsaenh/rsaenh.c:161:23: note: in definition of macro 'RSAENH_REGKEY'
 #define RSAENH_REGKEY "Software\\Wine\\Crypto\\RSA\\%s"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dll/win32/rsaenh/rsaenh.c:1107:5: note: 'sprintf' output between 26 and 285 bytes into a destination of size 260
     sprintf(szRSABase, RSAENH_REGKEY, pKeyContainer->szName);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~