[WIN32K]: Addendum to r75332 : fix variable usage without initialization error C4700 (certainly due to a copy-paste error), caught by MSVC compiler... CORE-13536
svn path=/trunk/; revision=75337